// ============================================================
//  App.jsx — THE PORTFOLIO UI
//  Do NOT edit this file.
//  To customise your portfolio, edit src/data.json instead.
// ============================================================
import data from "./data.json";

// ── Icon set (inline SVGs — no external dependency) ─────────
const Icon = ({ d, size = 20, ...props }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>
    {Array.isArray(d) ? d.map((path, i) => <path key={i} d={path} />) : <path d={d} />}
  </svg>
);
const Github = ({ size = 20 }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
    <path d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0 1 12 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z" />
  </svg>
);
const Linkedin    = ({ size = 20 }) => <Icon size={size} d={["M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z","M2 9h4v12H2z"]}><circle cx="4" cy="4" r="2" /></Icon>;
const Mail        = ({ size = 20 }) => <Icon size={size} d={["M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z","M22 6l-10 7L2 6"]} />;
const ExternalLink= ({ size = 16 }) => <Icon size={size} d={["M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6","M15 3h6v6","M10 14L21 3"]} />;
const FileText    = ({ size = 14 }) => <Icon size={size} d={["M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z","M14 2v6h6","M16 13H8","M16 17H8","M10 9H8"]} />;
const Code2       = ({ size = 20 }) => <Icon size={size} d={["M16 18l6-6-6-6","M8 6l-6 6 6 6"]} />;
const GraduationCap=({ size = 20 }) => <Icon size={size} d={["M22 10v6M2 10l10-5 10 5-10 5z","M6 12v5c3 3 9 3 12 0v-5"]} />;
const FolderGit2  = ({ size = 18 }) => <Icon size={size} d={["M9 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v5","M12 20v-6","M15 17l3 3 3-3","M15 17v-5"]} />;
const ChevronRight= ({ size = 16 }) => <Icon size={size} d="M9 18l6-6-6-6" />;

// ── Navbar ──────────────────────────────────────────────────
function Navbar() {
  return (
    <nav className="fixed top-0 left-0 right-0 z-50 bg-slate-900/80 backdrop-blur-md border-b border-slate-800">
      <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
        <span className="font-mono text-emerald-400 font-semibold text-sm tracking-widest uppercase">
          {data.studentName.split(" ")[0] === "ATTENDEE" ? "Portfolio" : data.studentName.split(" ")[0]}
          <span className="text-slate-500">.</span>dev
        </span>
        <div className="hidden sm:flex items-center gap-6 text-sm text-slate-400">
          {["About", "Skills", "Projects", "Education", "Contact"].map((s) => (
            <a
              key={s}
              href={`#${s.toLowerCase()}`}
              className="hover:text-emerald-400 transition-colors duration-200"
            >
              {s}
            </a>
          ))}
        </div>
        <a
          href={data.resumeUrl !== "PASTE YOUR GOOGLE DRIVE / DROPBOX RESUME LINK HERE" ? data.resumeUrl : "#"}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 text-xs font-medium px-4 py-2 rounded-full border border-emerald-500/50 text-emerald-400 hover:bg-emerald-500/10 transition-all duration-200"
        >
          <FileText size={13} />
          Resume
        </a>
      </div>
    </nav>
  );
}

// ── Hero ─────────────────────────────────────────────────────
function Hero() {
  return (
    <section
      id="hero"
      className="min-h-screen flex items-center justify-center relative overflow-hidden pt-16"
    >
      {/* Background grid */}
      <div
        className="absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage:
            "linear-gradient(#10b981 1px, transparent 1px), linear-gradient(90deg, #10b981 1px, transparent 1px)",
          backgroundSize: "60px 60px",
        }}
      />
      {/* Radial glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-emerald-500/5 rounded-full blur-3xl pointer-events-none" />

      <div className="relative z-10 max-w-6xl mx-auto px-6 flex flex-col lg:flex-row items-center gap-16">
        {/* Text */}
        <div className="flex-1 text-center lg:text-left">
          <p className="animate-fade-up delay-100 font-mono text-emerald-400 text-sm tracking-[0.3em] uppercase mb-4">
            &gt; Hello, world —
          </p>
          <h1 className="animate-fade-up delay-200 text-5xl sm:text-6xl lg:text-7xl font-black text-white leading-[1.05] mb-4">
            I&apos;m{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-teal-300">
              {data.studentName}
            </span>
          </h1>
          <p className="animate-fade-up delay-300 text-xl sm:text-2xl text-slate-400 font-light mb-6">
            {data.studentRole}
          </p>
          <p className="animate-fade-up delay-400 text-slate-400 text-base leading-relaxed max-w-xl mx-auto lg:mx-0 mb-10">
            {data.studentBio}
          </p>
          <div className="animate-fade-up delay-500 flex flex-wrap items-center justify-center lg:justify-start gap-4">
            <a
              href="#projects"
              className="group flex items-center gap-2 bg-emerald-500 hover:bg-emerald-400 text-slate-900 font-bold px-6 py-3 rounded-full transition-all duration-200 shadow-lg shadow-emerald-500/20"
            >
              View Projects
              <ChevronRight size={16} className="group-hover:translate-x-1 transition-transform" />
            </a>
            <a
              href="#contact"
              className="flex items-center gap-2 border border-slate-700 hover:border-emerald-500/50 text-slate-300 hover:text-white px-6 py-3 rounded-full transition-all duration-200"
            >
              Contact Me
            </a>
          </div>

          {/* Social icons */}
          <div className="animate-fade-up delay-500 flex items-center justify-center lg:justify-start gap-4 mt-8">
            {[
              { href: data.github, icon: <Github size={18} />, label: "GitHub" },
              { href: data.linkedin, icon: <Linkedin size={18} />, label: "LinkedIn" },
              { href: `mailto:${data.email}`, icon: <Mail size={18} />, label: "Email" },
            ].map(({ href, icon, label }) => (
              <a
                key={label}
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                aria-label={label}
                className="p-2.5 rounded-lg bg-slate-800/60 border border-slate-700/60 text-slate-400 hover:text-emerald-400 hover:border-emerald-500/40 transition-all duration-200"
              >
                {icon}
              </a>
            ))}
          </div>
        </div>

        {/* Avatar */}
        <div className="flex-shrink-0 animate-fade-up delay-300">
          <div className="relative">
            <div className="absolute -inset-1 rounded-full bg-gradient-to-br from-emerald-400 to-teal-500 blur-md opacity-60 glow-pulse" />
            <img
              src={data.avatarUrl}
              alt={data.studentName}
              className="relative w-48 h-48 lg:w-56 lg:h-56 rounded-full object-cover border-2 border-slate-700"
              onError={(e) => {
                e.target.src = `https://ui-avatars.com/api/?name=${encodeURIComponent(data.studentName)}&background=10b981&color=fff&size=200&bold=true&font-size=0.4`;
              }}
            />
          </div>
        </div>
      </div>

      {/* Scroll indicator */}
      <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-slate-600 animate-bounce">
        <span className="text-xs font-mono tracking-widest">scroll</span>
        <div className="w-px h-8 bg-gradient-to-b from-slate-600 to-transparent" />
      </div>
    </section>
  );
}

// ── Section Header ───────────────────────────────────────────
function SectionHeader({ icon, title, subtitle }) {
  return (
    <div className="mb-12">
      <div className="flex items-center gap-3 mb-2">
        <span className="text-emerald-400">{icon}</span>
        <span className="font-mono text-xs text-emerald-400 tracking-[0.3em] uppercase">{subtitle}</span>
      </div>
      <h2 className="text-3xl sm:text-4xl font-bold text-white">{title}</h2>
      <div className="mt-3 w-12 h-0.5 bg-emerald-400 rounded-full" />
    </div>
  );
}

// ── About ────────────────────────────────────────────────────
function About() {
  return (
    <section id="about" className="py-24 px-6">
      <div className="max-w-6xl mx-auto">
        <SectionHeader icon={<Code2 size={20} />} title="About Me" subtitle="// who I am" />
        <div className="bg-slate-800/40 border border-slate-700/60 rounded-2xl p-8 sm:p-10 backdrop-blur-sm">
          <div className="flex flex-col sm:flex-row items-start gap-8">
            <img
              src={data.avatarUrl}
              alt={data.studentName}
              className="w-24 h-24 rounded-xl object-cover border border-slate-700 flex-shrink-0"
              onError={(e) => {
                e.target.src = `https://ui-avatars.com/api/?name=${encodeURIComponent(data.studentName)}&background=10b981&color=fff&size=96&bold=true&font-size=0.4`;
              }}
            />
            <div className="flex-1">
              <h3 className="text-xl font-bold text-white mb-1">{data.studentName}</h3>
              <p className="text-emerald-400 font-mono text-sm mb-4">{data.studentRole}</p>
              <p className="text-slate-300 leading-relaxed text-[15px]">{data.studentBio}</p>
              <div className="flex flex-wrap gap-3 mt-6">
                <a href={`mailto:${data.email}`} className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-emerald-400 transition-colors">
                  <Mail size={14} /> {data.email}
                </a>
                <a href={data.github} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-emerald-400 transition-colors">
                  <Github size={14} /> GitHub
                </a>
                <a href={data.linkedin} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-emerald-400 transition-colors">
                  <Linkedin size={14} /> LinkedIn
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ── Skills ───────────────────────────────────────────────────
function Skills() {
  return (
    <section id="skills" className="py-24 px-6 bg-slate-800/20">
      <div className="max-w-6xl mx-auto">
        <SectionHeader icon={<Code2 size={20} />} title="Tech Stack" subtitle="// skills" />
        <div className="flex flex-wrap gap-3">
          {data.skills.map((skill, i) => (
            <span
              key={i}
              className="group flex items-center gap-2 px-4 py-2 rounded-full bg-slate-800/60 border border-slate-700/60 text-slate-300 text-sm font-medium hover:border-emerald-500/50 hover:text-emerald-300 hover:bg-emerald-500/5 transition-all duration-200 cursor-default"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 opacity-60 group-hover:opacity-100 transition-opacity" />
              {skill}
            </span>
          ))}
        </div>
      </div>
    </section>
  );
}

// ── Projects ─────────────────────────────────────────────────
function ProjectCard({ project, index }) {
  return (
    <div
      className="group relative bg-slate-800/40 border border-slate-700/60 rounded-2xl p-6 hover:border-emerald-500/30 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-emerald-500/5 flex flex-col"
      style={{ animationDelay: `${index * 100}ms` }}
    >
      {/* Card number watermark */}
      <span className="absolute top-5 right-6 font-mono text-5xl font-black text-slate-700/40 select-none group-hover:text-emerald-500/10 transition-colors">
        {String(index + 1).padStart(2, "0")}
      </span>

      <div className="flex items-start justify-between gap-4 mb-4">
        <div className="p-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
          <FolderGit2 size={18} className="text-emerald-400" />
        </div>
        <div className="flex items-center gap-2 z-10">
          {project.repoUrl && project.repoUrl !== "#" && (
            <a
              href={project.repoUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="p-1.5 text-slate-500 hover:text-emerald-400 transition-colors"
              aria-label="Repository"
            >
              <Github size={16} />
            </a>
          )}
          {project.liveUrl && project.liveUrl !== "#" && (
            <a
              href={project.liveUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="p-1.5 text-slate-500 hover:text-emerald-400 transition-colors"
              aria-label="Live site"
            >
              <ExternalLink size={16} />
            </a>
          )}
        </div>
      </div>

      <h3 className="text-lg font-bold text-white mb-2">{project.title}</h3>
      <p className="text-slate-400 text-sm leading-relaxed flex-1 mb-5">{project.description}</p>

      <div className="flex flex-wrap gap-2 mt-auto">
        {project.techStack.map((tech, i) => (
          <span
            key={i}
            className="px-2.5 py-0.5 text-xs font-mono rounded-md bg-slate-900/60 border border-slate-700/60 text-slate-400"
          >
            {tech}
          </span>
        ))}
      </div>
    </div>
  );
}

function Projects() {
  return (
    <section id="projects" className="py-24 px-6">
      <div className="max-w-6xl mx-auto">
        <SectionHeader icon={<FolderGit2 size={20} />} title="Projects" subtitle="// what I've built" />
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {data.projects.map((project, i) => (
            <ProjectCard key={i} project={project} index={i} />
          ))}
        </div>
      </div>
    </section>
  );
}

// ── Education ────────────────────────────────────────────────
function Education() {
  return (
    <section id="education" className="py-24 px-6 bg-slate-800/20">
      <div className="max-w-6xl mx-auto">
        <SectionHeader icon={<GraduationCap size={20} />} title="Education" subtitle="// background" />
        <div className="flex flex-col gap-5">
          {data.education.map((edu, i) => (
            <div
              key={i}
              className="group flex gap-6 bg-slate-800/40 border border-slate-700/60 rounded-2xl p-6 hover:border-emerald-500/30 transition-all duration-300"
            >
              {/* Timeline dot */}
              <div className="flex flex-col items-center pt-1 gap-2 flex-shrink-0">
                <div className="w-3 h-3 rounded-full bg-emerald-400 border-2 border-slate-900 group-hover:scale-110 transition-transform" />
                {i < data.education.length - 1 && (
                  <div className="w-px flex-1 bg-slate-700/60 min-h-[24px]" />
                )}
              </div>
              <div className="flex-1">
                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-1 mb-2">
                  <h3 className="text-base font-bold text-white">{edu.institution}</h3>
                  <span className="text-xs font-mono text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-0.5 rounded-full flex-shrink-0">
                    {edu.period}
                  </span>
                </div>
                <p className="text-sm text-emerald-300/80 font-medium mb-2">{edu.degree}</p>
                <p className="text-sm text-slate-400 leading-relaxed">{edu.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ── Contact ──────────────────────────────────────────────────
function Contact() {
  return (
    <section id="contact" className="py-24 px-6">
      <div className="max-w-2xl mx-auto text-center">
        <SectionHeader
          icon={<Mail size={20} />}
          title="Get In Touch"
          subtitle="// contact"
        />
        <p className="text-slate-400 text-base leading-relaxed mb-10">
          I&apos;m currently open to new opportunities. Whether you have a project idea, a question, or just want to say hi — my inbox is always open!
        </p>

        <a
          href={`mailto:${data.email}`}
          className="group inline-flex items-center gap-3 bg-emerald-500 hover:bg-emerald-400 text-slate-900 font-bold px-8 py-4 rounded-full transition-all duration-200 shadow-lg shadow-emerald-500/20 text-lg mb-12"
        >
          <Mail size={20} />
          {data.email}
          <ChevronRight size={16} className="group-hover:translate-x-1 transition-transform" />
        </a>

        <div className="flex items-center justify-center gap-6">
          {[
            { href: data.github, icon: <Github size={20} />, label: "GitHub" },
            { href: data.linkedin, icon: <Linkedin size={20} />, label: "LinkedIn" },
            { href: `mailto:${data.email}`, icon: <Mail size={20} />, label: "Email" },
          ].map(({ href, icon, label }) => (
            <a
              key={label}
              href={href}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={label}
              className="p-3 rounded-xl bg-slate-800/60 border border-slate-700/60 text-slate-400 hover:text-emerald-400 hover:border-emerald-500/40 transition-all duration-200"
            >
              {icon}
            </a>
          ))}
        </div>
      </div>
    </section>
  );
}

// ── Footer ───────────────────────────────────────────────────
function Footer() {
  return (
    <footer className="border-t border-slate-800 py-8 px-6 text-center">
      <p className="text-slate-600 text-sm font-mono">
        <span className="text-emerald-400/50">&lt;</span>
        built by{" "}
        <span className="text-slate-400">{data.studentName}</span>
        <span className="text-emerald-400/50"> /&gt;</span>
      </p>
    </footer>
  );
}

// ── App ──────────────────────────────────────────────────────
export default function App() {
  return (
    <div className="min-h-screen bg-slate-900 text-slate-100">
      <Navbar />
      <Hero />
      <About />
      <Skills />
      <Projects />
      <Education />
      <Contact />
      <Footer />
    </div>
  );
}
